[package]
name = "flac-decoder"
version = "0.1.0"
authors = ["Bojan Šernek <bojan@distopiksound.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.78"

console_error_panic_hook = "0.1.6"

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
